CREATE TABLE IF NOT EXISTS person
(
    id           bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    username     varchar,
    created_by   varchar,
    created_date timestamp with time zone,
    changed_by   varchar,
    changed_date timestamp with time zone
)